"""
Django settings for plantify_admin project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ag#0bwsn29zcsg@rkmf)$s_c(i*sm#2ksaaw_wueyyzg8!sp2y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'dashboard.apps.DashboardConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


FIREBASE_TYPE = "service_account"
FIREBASE_PROJECT_ID = "plantify-ebc63"
FIREBASE_PRIVATE_KEY_ID = "f335b84d6531472fe83f5ace0a97f59a4700fc5c"
FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCqjRV7b+E2ALke\nUvyXXnj5OJ8ShhMl3XsR5u23QUBqo5rLtskbyfNhGS/508aCVhch+HwCxxAKG75+\nRAoFHXwwcFasmpTCYo+Uv0xHEeF4O23j4muPZOHhAb8+SoXB8NLsCG/FvxQZgS3I\nzLQvIpLVz10HKEWtELoVzn78f29qNtaCWw/L0sifSDIBHjbvkH/FGgQ4fgpx2Sni\n8LiJsEZG1v49k9OqbQk69Le06fcV6FNQTjd+Cij6pvMCU75bAOnHlJpQcMj7mDEC\nXJ+pDf8IO6YOQE6Ae4/1YVEYSeMPVwg+LzqfQoXsw88q4EPLKMPTcZ6JUKMvRjZl\nmZ6sclxbAgMBAAECggEACEFQSbYWdGWK5aUGVTyn5gbvwCxIL1GDRvsNWjeTgCCP\neg53Y9vIZtSaxgtnn4sTjzvhThsc3iMN+zuc2+GGT4E92MNEsbdRPtXBl0EOJPfa\nGlPXzqGHQ2Zbv46eNHnNI8qcFQ9qJXqOC5rzmm0gfAPk+1c02YB77q6c5pOJLN61\nZlowrYnD/D3gtOzWlFGVGSXHkHxpxXzvfg3pbLl94buKGUTY8uiJ0zMfqmnjWMVW\nQrolzMitRG2f4tuE46O8N8yju+7/zLdSrgRY5mQHrq99nqUybzXOdJVfjvJIZBzq\n9KXkrlbBJwvOPwdwMPn0Yk6rheuP9PGa22IRN4NbHQKBgQDY5qKAvpWklfziIxut\nZGd34BhbP5XkHvEZT22/57e+f2RNzeKN/zMK4JhIMw0hZvGomGeCgBIDNcVBxjUk\nEV41oIzWQF8U/f0z79/NNiQHnHUMfihjfe9O2cKSX3LHGbaaQ9+N+hobx+rFypYL\nM9mrbL9mSrwafBrr0GY4MSvblwKBgQDJS4lKu4hd1O3/b87LJECTWxjDmJBhB275\nGzFXyGDUPVHNpwSbMTg9WTjRCFWqMv2T6jZ6iuB1FzFfohgWFcZHIoJSkCNDisG0\n/cx+unLKbPxc8doKQzYGPqUmPKA7R74tGf+53I0vZUPIHXQuhg3KtFO7Pkp1o+lV\nZdkq4G3t3QKBgQCZv0pbRj0esG7UARziWLR7Ja8+JyFh1YkDbukVyfPWJcj82b8I\n9mfBAxkOvJlHHwiXgIiG2a9q9ReBGzWZ/nGwQ8DxMinz4GI2CYezl/gMKRxTIa4R\ncDhMxVEFnoDmntRwH0J9ClatcJV7ZLHc+QEHYYt+v+T8RRJ0K4H5vOkguwKBgHVG\nYth9Zbd1JKvbUhmcJ1syibz7F7LQB+Ft7FN+VJuSliRAmDhqdp+XabivKGmeh4oz\nvEWsv5S4THWxFGNZkElFW7QKceEZ6D0wWIHE0rgIwwbLiQLNoZ4FxWX/kEK5S50v\nNoPscP0Z/GGMd3HbfBGK+fVvFyZutrSgP+PxGVqpAoGBAI1N+ZBfM3rRNdFpUzlA\nh5Oo+RQqiGNQjC3FliMU5lAUBNVYDTHJx7p5g08W9FGyKT7N08zKf6P0L103KDVp\nBO4borA3sliiqtVYXZ9j8lix68wSJnHppMsOiz6pWDHFWZd+qT1BqD0dEYB4Y9wz\ngRu6gjvxrqpL+ooizJjevByj\n-----END PRIVATE KEY-----\n",
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-uqt4o@plantify-ebc63.iam.gserviceaccount.com"
FIREBASE_CLIENT_ID = "110346106438946268465"
FIREBASE_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
FIREBASE_TOKEN_URI = "https://oauth2.googleapis.com/token"
FIREBASE_AUTH_PROVIDER_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
FIREBASE_CLIENT_CERT_URL = "https://www.googleapis.com/robot/v1/metadata/x509/service-account-email%40project-id.iam.gserviceaccount.com"

LOGIN_URL = 'admin:login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'plantify_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plantify_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_REDIRECT_URL = 'dashboard'
# LOGOUT_REDIRECT_URL = '/admin/login/'